# This is a basic workflow to help you get started with Actions

name: Manually build apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #  branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]

  # В ручную
  workflow_dispatch:
  
defaults:
 run:
  working-directory: ./app_ci_cd

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build APk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          # lutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --split-per-abi
      - run: ls build/
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          name: manual
          commit: manual 
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.cidi_flutter}}
